# =========================
# LOCAL SDK OVERRIDES
# =========================
sdk:
  security:
    enabled: true
    method-security-enabled: false
    cors:
      enabled: false

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/java_boilerplate}

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}

logging:
  structured:
    # =========================
    # LOCAL LOGGING OVERRIDES
    # =========================
    format:
      console: ""
    enabled: true
    auto-configure-format: false
